### ISSUE TITLE
partitions/area's not working

### ISSUE THREAD

**Issue by microc1** [flareman/homebridge-caddx-interlogix#7] opened 2021-04-11 22:11 UTC
Partition/area 1 works correctly.  A larger system with multiple partitions does not work correctly.  They appear as accessories but the status is incorrect (ie showing armed when disarmed) and arming or disarming displays "no response" or "This accessory is not responding".

**Comment by flareman** [comment] 2021-04-14 09:44
I'm sorry to hear that; I could use your help debugging, if that's okay with you, seeing as my installation has only one area. Could you please post a screenshot of your web interface's area naming page? In addition, I would like you to run Homebridge with the debug switch (-D) and copy/paste the console output after restart and trying to read/set an area status.

I'll try to work on this during the weekend, seeing as day job schedule is hectic this week.

**Comment by microc1** [comment] 2021-04-15 23:24
Have spent a bit of time looking at this but not fully debugged (my background is C coding not js) 
There seems to be an incorrect brackets in the Math.floor in the NX595ESecuritySystem.   

current code:
bank_state: bank_states.slice(Math.floor((i / 8) * 17), (Math.floor((i / 8) * 17) + 17)),

should be more like:
bank_state: bank_states.slice((Math.floor(i / 8) * 17), (Math.floor(i / 8) * 17 + 17)),

Stepping through the web front end on the NX595E around the same Math.floor in status.js shows the difference.  The maths.floor is only on the i /8, then * 17 current code is doing a maths.floor of the complete i / 8 * 17 which results in a completely different number.  The stored bank_state should be the same for area 1-3 and the mask is how the code extracts the actual status (this code sections does my head in trying to follow it.....) 

There is still a second problem in that the async retrieveAreas seeems to be only called once on startup so the processAreas keeps using old data in the area parsing and times out for area's > 1.  (I have not fully looked at how this works for area 1 but not the other area's).   

Also I think the sequence number storing should be the same for each area rather as there is only 1 sequence number in the NX595E front end.  Not sure what the sequence number does at this point.

change:
sequence: sequence[i],
to:
sequence: sequence[0],

**Comment by flareman** [comment] 2021-04-26 08:29
Have you by any chance been able to procure the debug output and the screenshots that I've asked you for?

areaSequence is an array in the front-end that contains the sequence values for every area in the system; every time an area changes its status (i.e. from ready to not ready and so on), the sequence increases by one, and the plugin uses this to detect areas where changes have occurred. retrieveAreas runs only once in the beginning because registered areas do not change while the system is online, so there is no need for further retrieval: when the plugin starts up it parses all areas (and it should detect any areas above the first one as well), and then just needs to update any areas where the related sequence number changes.

The actual system for retrieval of bank states is a major pain, both for areas and for zones. Essentially the security system uses bitbanks internally to store the necessary data as flags, and uses a rolling mask to single out the necessary data and parse it. Your observation regarding the Math.floor syntax does have merit; I'll make sure to take a look into it while waiting for your input :)

**Comment by flareman** [comment] 2021-05-18 12:59
Version 1.1.6 is live; please try it out and see if your issue with area arming is resolved.

I would appreciate some additional input from other users who have multiple areas in their setup as well, to make sure that the problem is fixed without introducing any new pitfalls.

**Closed as completed** 2021-06-01 19:25 UTC
Labels: bug
